todoapp/urls.py
from django.urls import path
from . import views
app_name = 'todoapp'

# urlpatterns = [
#     path('', views.index, name='index'),
#     path('todo/', views.todoappView, name='todo'),
#     path('addTodoItem/',views.addTodoView), 
#     path('deleteTodoItem/<int:id>/', views.deleteTodoView), 
#   path('updateTodoItem/<int:id>/', views.updateTodoView),
# ]# In your app's urls.py file


urlpatterns = [
    path('', views.index, name='index'),  # Assuming this is your index view
    path('todo/', views.todoappView, name='todo'),
    path('addTodoItem/', views.addTodoView, name='add_todo_item'),
    path('deleteTodoItem/<int:id>/', views.deleteTodoView, name='delete_todo_item'),
    path('updateTodoItem/<int:id>/', views.updateTodoView, name='update_todo_item'),  # Define the URL pattern for update view
]

todoproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls',)),
]

todoapp/models.py
from django.db import models


# Create your models here.
class TodoListItem(models.Model):
    content = models.TextField() 

todoapp/views.py
from django.shortcuts import render
from .models import TodoListItem 
from django.http import HttpResponseRedirect 
# Create your views here.
def index(request):
    return render(request, 'index.html')



def todoappView(request):
    all_todo_items = TodoListItem.objects.all()
    return render(request, 'todolist.html',  {'all_items':all_todo_items})


def addTodoView(request):
    new_item = TodoListItem()
    new_item.content = request.POST.get('content')
    new_item.save()
    return HttpResponseRedirect('/todo/') 


def deleteTodoView(request, id):
    y = TodoListItem.objects.get(id= id)
    y.delete()
    return HttpResponseRedirect('/todo/') 


def updateTodoView(request, id):
    item = TodoListItem.objects.get(id=id)
    item.content = request.POST.get('content')
    item.save()
    return HttpResponseRedirect('/todo/')

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <title>Document</title>
</head>
<body style="background-color: lightblue;">
    
<div class="container">
    <div class="card text-center" style="margin-top: 200px;">
        <div class="card-header">
          Hello!
        </div>
        <div class="card-body">
          <h5 class="card-title">Welcome to the app</h5>
          <p class="card-text">Make life easier by creating ToDo List</p>
          <a href="{% url 'todoapp:todo' %}" class="btn btn-primary">Start Now!</a>
        </div>
        <div class="card-footer text-muted">
          2 days ago
        </div>
      </div>
</div>

    
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>    
</body>
</html>

templates/todolist.html
{% comment %}  This is made by Siddharth R Bhardwaj {% endcomment %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <title>Todo List</title>
</head>
<body style="background-color: lightblue;">
    
<div class="container">

    <div class="row" style="margin-top: 20px;">
        <div class="col">

            <div class="row">
                <form class="form-inline" action="/addTodoItem/" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-8">
                            <div class="form-group mx-sm-3 mb-2">
                                <label for="content" class="sr-only"></label>
                                <input type="text" class="form-control" name="content" placeholder="Add Todo">
                            </div>
                        </div>
                        <div class="col-4" style="margin-top: 25px;">
                            <button type="submit" class="btn btn-primary mb-2">Add Todo</button>
                        </div>
                    </div>
                </form>
            </div>

            {% for i in all_items %} 
            <div class="row">
                <div class="col-1"></div>
                <div class="col-6">
                    <div class="card text-white bg-dark mb-3">
                        <div class="card-body">
                            <form action="/updateTodoItem/{{ i.id }}/" method="post">
                                {% csrf_token %}
                                <input type="text" class="form-control" name="content" value="{{ i.content }}">
                                <button type="submit" class="btn btn-primary mt-2">Update</button>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="col-2">
                    <form action="/deleteTodoItem/{{ i.id }}/" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                            </svg>
                        </button>
                    </form>
                </div>
                <div class="col-3"></div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>    
</body>
</html>